package Naushad;

import java.awt.FlowLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


public class GUIwithJFrame extends JFrame{

	private static final long serialVersionUID = 1L;  //generated by eclipse

	public GUIwithJFrame(){
		super("This is the fancy title for JFrame");
		setLayout(new FlowLayout());
		
		JLabel item = new JLabel("Welcome to JFrame");
		item.setToolTipText("This is that text you get shown when you hover over a component");
		add(item);
		
		JTextField item1=new JTextField(10);
		add(item1);
		
		JTextField item2=new JTextField("TextField");
		add(item2);
		
		JTextField item3=new JTextField("Uneditable",10);
	    item3.setEditable(false);
		add(item3);
		
		JPasswordField item4 = new JPasswordField("mypass",20);
		add(item4);
	}

}
